# Generated by Django 4.2.16 on 2024-10-14 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=27)),
                ('parcels', models.IntegerField()),
            ],
        ),
    ]
